### ISSUE TITLE
Unable to launch 2020 WinGCLC executable

### ISSUE THREAD

**Issue by sw3aterCS** [janicicpredrag/gclc#1]
I downloaded the 2020 Windows package from your website (http://poincare.matf.bg.ac.rs/~janicic/gclc/) and was unable to run the command line executable. The following error box popped up:
![image](https://user-images.githubusercontent.com/29156621/102704621-b22ca380-4232-11eb-9cd9-f3f0509efb8b.png)
Preliminary web searching seems to imply that this might due to a missing flag from when the executable was compiled: https://stackoverflow.com/questions/4702732/the-program-cant-start-because-libgcc-s-dw2-1-dll-is-missing
I don't think this is an issue on my end as the 2015 version of GCLC works as normal.

**Comment by janicicpredrag** [comment]
Thanks. Now the pre-built versions for Windows (and in the distribution available from the web) are built using static linking 
(-static-libgcc -static-libstdc++). The source files have not been changed, so those who build gclc can still decide on the linking. Hope this will work for your computer. You might still need to have available some Qt dynamic libraries.
