### ISSUE TITLE
Minor: 

### ISSUE THREAD

**Issue by CoghettoR** [janicicpredrag/gclc#10]
this code

```
point A 10 10
point B 40 10
cmark_lt A
cmark_lt B
line lAB A B
drawsegment A B
drawdashline lAB
midpoint C A B
cmark_lt C
circle cBC B C
drawdashcircle cBC
intersec2 D D2 lAB cBC
cmark_lt D
circle cDA D A
drawdashcircle cDA
circle cAB A B
drawdashcircle cAB
intersec2 P2 P cAB cDA
cmark_t P
foot Q P lAB
cmark_lt Q
drawdashline P Q
midpoint R Q B
cmark_lt R
prove { same_length A Q R B }

```
 is of course out of context: the (-a) option confirms it.
It is therefore not of particular interest for an automatic verification of proof
but it seems to me that the options (-w) and (-g) crash  (segmentation fault) gclc and gclc-win (linux version).

**Comment by janicicpredrag** [comment]
The algebraic provers (currently) do not support conjectures involving intersection between two circles. Now, the fix has been made and this is reported for conjectures involving intersec2 for two circles.
