### ISSUE TITLE
1.1.0 Ubuntu 22.04 doesn't work

### ISSUE THREAD

**Issue by undefinedactive** [janicicpredrag/gclc#15]
I get this message on Ubuntu 22.04 LTS after trying to launch `gclc-gui` in terminal.
`./gclc-gui: /lib/x86_64-linux-gnu/libQt6Core.so.6: version 'Qt_6.6' not found (required by ./gclc-gui)`

I tried installing qt6 by `sudo apt install qt6-base-dev`
https://askubuntu.com/questions/1434956/install-qt6-on-22-04 .

And later realized that Ubuntu 22.04 LTS only supports qt version `6.2.4`  (https://packages.ubuntu.com/search?keywords=qt).

Version 1 works fine.

I noticed that the difference between version 1 and 1.1.0 is qt5 vs qt6. Please update `README.md` to reflect that.

**Comment by janicicpredrag** [comment]
It could be that your Qt6 libs have not been installed in /lib/x86... but in /home/.../Qt/... and they cannot be dynamically linked. Maybe something like this could help:
sudo ldconfig /home/../Qt/6.7.0/gcc_64/lib
