### ISSUE TITLE
1.1.0 Windows doesn't work

### ISSUE THREAD

**Issue by undefinedactive** [janicicpredrag/gclc#16]
I tried launching 1.1.0 and get this crash messages:

`gclc-gui.exe`
![entry_point_not_found](https://github.com/janicicpredrag/gclc/assets/161751841/5b149868-ff53-4650-b632-735df34733c4)

`Qt6Gui.dll`
![entry_point_not_found1](https://github.com/janicicpredrag/gclc/assets/161751841/2e59a173-8f19-4f13-8919-4e592e5453f5)

`Qt6Widgets.dll`, `Qt6Core.dll`
![entry_point_not_found2](https://github.com/janicicpredrag/gclc/assets/161751841/f85377dd-c12e-4378-b7d2-4bdb3ee14a0c)

After accepting `OK` the program crashes.

Version 1 works fine.

**Comment by janicicpredrag** [comment]
Some users before also had issues with dynamic link libraries.
