### ISSUE TITLE
Documentation: default unit of length

### ISSUE THREAD

**Issue by zingchen** [janicicpredrag/gclc#3]
Hello. I was about to read the Quick Start chapter to get the basic idea, But after reading the manual entirely, I'm still facing difficulty understanding the introductory example.
``` 
point A 40 85
```
I have no idea how large is 40 (or 85). 40 what? Meters? Or feet? or typography points? 

40 abstract length units, I know. But what is the default scale between the abstract unit to a concrete (physical) unit? And what command, if any, can redefine this (default) scale?

Coming from an engineering background, I know that some CAD software (SketchUp and NanoCAD for instance) has quite a limited range of the ratio between the smallest and the largest line segments of a drawing project (10^6 to be concrete). Therefore it is very important to choose the correct scale at the very beginning. Applying a scale of quantum physics or chemistry (such as drawing an atom or molecule) to industrial design (furniture, machines) or architecture (building, bridge) would results in catastrophic loss of accuracy.

Even an illustration to a purely mathematical concept, such as a Venn diagram, needs a scale!

**Comment by zingchen** [comment]
So after a day experimenting with WinGCLC 2009 (which BTW is the only pre-built version that runs on my Windows computer) I 'discovered' that the default scale is 1 unit = 1 mm, assuming that the default drawing size is 140 x 100 mm.

I suggest that this information (the default size of drawings and the the scale) is included in the manual, best to the introductory example.

**Comment by janicicpredrag** [comment]
Thank you for the feedback. you are right, it is strange that the units were not mentioned in the introductory examples (and that it remained unnoticed for so long). I fixed this and updated the manual (I haven't build again the pre-built versions).

**Comment by ubavic** [comment]
I would sugest to add documentation source files to the repo, instead compiled PDFs. You could provide complied PDF with releases. GitHub actions as [this one](https://github.com/marketplace/actions/github-action-for-latex) can easily automate this process. (I have some experience with similar setup and I could help you implement this).

I would recommend similar thing for gclc binaries. Instead having executables in repository, you could build automatically them with actions (for example every time master branch get a new commit or a new tag).

**Comment by janicicpredrag** [comment]
Good suggestion. I've just added the "manual" folder to the repo. Your help will be welcome, thanks.
