### ISSUE TITLE
onsegment A B C ==> collinear A B C ?

### ISSUE THREAD

**Issue by CoghettoR** [janicicpredrag/gclc#4]
Is it true that if we have "segment B A C" then "collinear A B C" ? et "collinear "B A C" ... ?

```
point A 100 20
point B 40 20
onsegment C A B
prove { collinear A B C }
```

```
Input file: prove09.gcl
Output file: prove09.pic
Log file: gclc.log

Starting point number: 1

- The conjecture given to prove is ill-formed or includes a point 

that is not constructed by commands supported by the prover. (Line: 4, position: 7)
```
Indeed (gclc_man.pdf, section 6.3 "Geometry Quantities and Stating Conjectures"):

> 
> The conjecture can involve geometry quantities only over points and lines
> already introduced within the current construction, and by using (only) the
> following commands: point, line, intersec, midpoint, med, perp, foot, parallel, translate, towards, online.
> 

But, if we add/replace in the 3 files

- source/GCLCEngine/BasicConstructions.cpp
- source/TheoremProver/TheoremProver.cpp
- source/TheoremProver/TheoremProver.h

In source/GCLCEngine/BasicConstructions.cpp, procedure GCLCError CGCLC::get_onsegment():

```
_REPLACE_
 k = ((double)rand() / RAND_MAX);
  return Let(sPointName, GCLC_POINT, x1 + k * (x2 - x1), y1 + k * (y2 - y1), 0.00,
             0.00, 0.00, 0.00);
_BY_
 k = ((double)rand() / RAND_MAX);
      //-------- Support for the prover ----------
    if (ProvingTheorem())
    AddProverCommand(online, sPointName, o1.name, o2.name, d2s(k, -1));
    //-------- End of support for the prover ---
  return Let(sPointName, GCLC_POINT, x1 + k * (x2 - x1), y1 + k * (y2 - y1), 0.00,
             0.00, 0.00, 0.00);
```

in source/TheoremProver/TheoremProver.cpp, procedure bool CTheoremProver::AddProverCommand
```
_REPLACE_
  if (type == online) {
    string sConstantName;
    sConstantName = "r_{" + i2s(m_iPointCounter++) + "}";
_BY_
  if (type == online || type == onsegment) {
    string sConstantName;
    sConstantName = "r_{" + i2s(m_iPointCounter++) + "}";

```
and
in source/TheoremProver/TheoremProver.h
```
__ADD__ "onsegment"
enum eGCLC_prover_command {
  p_constant,
  p_point,
  p_line,
  p_inter,
  p_pratio,
  p_tratio,
  p_foot,
  online,
  onsegment,
  midpoint,
  med,
  perp,
  parallel,
  // new commands for algebraic methods 08.2007
  p_circle,
  oncircle,
  p_interlc,
  p_bis
};
```

now:

```
point A 100 20
point B 40 20
onsegment C A B
prove { collinear A B C }
```
We have the following result:
```
Starting point number: 1

The theorem prover based on the area method used.
Number of elimination proof steps:      1
Number of geometric proof steps:        3
Number of algebraic proof steps:        4
Total number of proof steps:            8

Time spent by the prover: 0.000 seconds
The conjecture successfully proved.
```
What do you think?

**Comment by janicicpredrag** [comment]
Dear Roland,
I merged your changes, but then I reverted them, I am sorry. 
I realized that you don't pass a constraint 0<k<1 to the prover and actually the implemented provers cannot use such additional constraints. So, with your changes, the points that is constructed by "onsegment" will be treated equally as if it was constructed by "online". 
Predrag

**Comment by CoghettoR** [comment]
Dear Predrag,

Indeed, 
but I don't want to prove "more" with "onbetween -> oncolinear" because indeed the 3 methods of the gclc assistant proof are not compatible with "onbetween".
I had indeed noted that (in Predrag Janicic, Julien Narboux et Pedro Quaresma. « The area method : a recapitulation ».
In : Journal of Automated Reasoning 48.4 (2012), p. 489-532):

> The axiom system used by Chou, Gao and Zhang [. . .] is a semi-analytic axiom system
> with (only) points as primitive objects (lines are not primitive objects as in Hilbert’s axiom
> system). The axiom system contains the axioms of field, so the system uses the concept of
> numbers, but it is still coordinate free. The field is not assumed to be ordered, hence the
> axiom system has the property of representing an unordered geometry. This means that,
> for instance, one cannot express the concept of a point being between two points (unlike
> in Hilbert’s system).

When I proposed this little "onbetween->oncolinear" change, I was thinking of something else entirely:

I was preparing a graph on Pappus' theorem and I had used "oncollinear" but the graph was not very readable because, randomly, some points were no longer visible on the "*.eps" file.

but I wanted to use "prove" at the same time. Mathematically, it seemed plausible to get validity with "prove" (with "-a" option) even when I had chosen the "onbetween" option instead of "oncolinear".

In the code below, the lines " # ... onbetween" must be uncommented in two places with the one below and it was possible to keep the "prove" function with "onbetween" in this case.

I'm sorry about that. Perhaps I should have presented my motivation initially.
I completely understand your refusal: the addition of "onbetween" could make one think that the proof assistant can also manage and prove that a point is between two other points, which is not (yet :-)?) possible.

Roland
```
point A 10 20
point B 50 80
onsegment C A B
%online C A B
cmark_lt A 
cmark_lt B
cmark_lt C
drawline A B
point D 60 15
point E 100 75
onsegment F D E
%online F D E
cmark_lt D 
cmark_lt E
cmark_lt F
drawline D E
line lAE A E
line lAF A F
line lBD B D
line lBF B F
line lCD C D
line lCE C E
drawdashline lAE
drawdashline lAF
drawdashline lBD
drawdashline lBF
drawdashline lCD
drawdashline lCE
intersec P lBF lCE
intersec Q lAF lCD
intersec R lAE lBD
cmark_lt P
cmark_lt Q
cmark_lt R
drawline P Q
prove { collinear P Q R }

```

**Comment by janicicpredrag** [comment]
Dear Roland, 

Thank you very much for these additional thoughts. I completely agree with you. If we treat "onsegment" the way you proposed, and if the prover say the conjecture is valid then indeed it is. But if it say that the conjecture is invalid it still does not mean that it is indeed invalid. In other words, the area method would not be a decision procedure for such extended input language. 
I understand that we might be tempted to slightly extend the scope of the method this way, but that could indeed introduce some misinterpretations or confusion. So, it seems to me that it is better not to apply this change.

Thank you again for your interesting contribution and thank you for looking at and using GCLC. 
Predrag
