### ISSUE TITLE
Minor: Indication "Out of scope"

### ISSUE THREAD

**Issue by CoghettoR** [janicicpredrag/gclc#7]
file: trisect1.gcl
```
dim 100 80
point A 10 10
point B 70 10
cmark_lt A
cmark_rt B
line lAB A B
drawsegment A B
point C 15 20
cmark_lt C
line lAC A C
drawdashline A C
circle cCA C A
intersec2 D D2 cCA lAC
cmark_t D
circle cDC D C
intersec2 E E2 cDC lAC
cmark_t E
line lEB E B
drawdashline E B
parallel lD D lEB
drawdashline lD 
intersec F lD lAB
cmark_rt F
parallel lC C lEB
drawdashline lC
intersec G lC lAB
cmark_rt G
prove { same_length F B G F }
```

with gclc (gclc trisect1.gcl -a): there is no indication that "Out of scope":
```
Input file: trisect1.gcl
Output file: trisect1.pic
Log file: gclc.log

Starting point number: 1

The theorem prover based on the area method used.
Number of elimination proof steps:    232
Number of geometric proof steps:      405
Number of algebraic proof steps:     3075
Total number of proof steps:         3712

Time spent by the prover: 3.582 seconds
The prover output is written in the file trisect1_proof.tex.

File 'trisect1.gcl' successfully processed.
Ending point number: 425

Transcript written on gclc.log.
```
Of course the information is in the log file as well as in the trisect1_proof.tex file or with gclc-gui.
On the other hand, when this is the case, there is the output display at this location reports "The conjecture not proved," "The conjecture successfully proved." ok

Regards,

**Comment by janicicpredrag** [comment]
Indeed, there was a missing information if the conjecture is out of scope of the prover (in the report to the standard output). Hopefully fixed. (I don't understand the last sentence)

**Comment by CoghettoR** [comment]
_Indeed, there was a missing information if the conjecture is out of scope of the prover (in the report to the standard output). Hopefully fixed:_ yes, thanks.

_(I don't understand the last sentence):_ Sorry, my transcription error.
