### ISSUE TITLE
Conjecture proven with wu's method and Groebner bases but crash with area method

### ISSUE THREAD

**Issue by CoghettoR** [janicicpredrag/gclc#8]
```
point A 10 40
point B 80 40
cmark_lt A
cmark_lt B
line lAB A B
drawsegment A B
point C 30 70
cmark_lt C
line lAC A C
drawdashline lAC
parallel lB B lAC
drawdashline lB
midpoint D A B
cmark_rt D
line lCD C D
drawdashline lCD
intersec E lCD lB
cmark_lt E
midpoint F A C
cmark_lt F
midpoint G B E
cmark_rt G
line lCG C G
drawline lCG
intersec H lCG lAB
cmark_rt H
line lEF E F
drawline lEF
intersec I lEF lAB
cmark_rt I
prove { same_length I A I H }
```
I think this file with "gclc -a" stops the program.

I have no problem with "gclc -w" or "gclc -g": in both cases I get the answer "The conjecture successfully proved."

Regards,

**Comment by janicicpredrag** [comment]
Thank you, indeed there was a bug in the area method, in the case when there are nested conjectures. The bug was introduced in the latest version before the code went open source. Now the bug is hopefully fixed.
