### ISSUE TITLE
Conic intersection

### ISSUE THREAD

**Issue by katepano** [janicicpredrag/gclc#86]
Hello and thanks for this excellent software. 
This is not an issue but rather a request. I am missing a command to find the intersections of two conics. 
Is it possible to have it at a new release?
thanks
dimitris

**Comment by janicicpredrag** [comment]
Dear Dimitris,

**Comment by janicicpredrag** [comment]
Dear Dimitris, 
Thank you for your nice words. Intersection of two conics is not trivial, I've just added it to my GCLC list. Unfortunately not for a near future, but  hopefully at some point :)
Sincerely, Predrag
